In [28]:
def price_check(price):
    #Price must be Nx5 Matrix
    
    price_go_up_list = []
    
    for i in range(len(price)):
        if price[i] > price[i - 1]:
            price_go_up_list.append(1)
        else:
            price_go_up_list.append(0)
            
    return price_go_up_list

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
%matplotlib inline

In [5]:
start = '2015-05-01'
end = '2020-09-11'

tsla = yf.download('TSLA', start, end)

[*********************100%***********************]  1 of 1 completed

In [13]:
mean_open = []
mean_high = []
mean_low = []
mean_AdjClose = []

for i in range(len(tsla['Open'])):
    mean_open.append(tsla['Open'][i])
    mean_high.append(tsla['High'][i])
    mean_low.append(tsla['Low'][i])
    mean_AdjClose.append(tsla['Adj Close'][i])

In [11]:
tsla_means = pd.DataFrame()

In [23]:
mean_op = []
mean_hi = []
mean_lo = []
mean_clo = []

for i in range(5, len(mean_open)):
    mean_op.append(tsla['Open'][i-5:i].mean())
    mean_hi.append(tsla['High'][i-5:i].mean())
    mean_lo.append(tsla['Low'][i-5:i].mean())
    mean_clo.append(tsla['Adj Close'][i-5:i].mean())
    

data_mean = {'Open mean' : mean_op,
             'High mean' : mean_hi,
             'Low mean' : mean_lo,
             'Adj Close Mean' : mean_clo}

In [25]:
tsla_means = pd.DataFrame(data_mean)

In [26]:
tsla_means.head()

   Open mean  High mean  Low mean  Adj Close Mean
0  46.414799    46.9344   45.2008       45.838800
1  46.039200    47.1180   45.0040       46.268800
2  46.281200    47.3836   45.5356       46.692000
3  46.605600    47.7096   45.8636       47.051199
4  46.699600    47.9836   46.2260       47.522800

In [30]:
truth_list = price_check(mean_clo)
truth_list

[0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 ...]

In [31]:
tsla_means['Price go UP'] = truth_list

In [32]:
tsla_means

       Open mean   High mean    Low mean  Adj Close Mean  Price go UP
0      46.414799   46.934400   45.200800       45.838800            0
1      46.039200   47.118000   45.004000       46.268800            1
2      46.281200   47.383600   45.535600       46.692000            1
3      46.605600   47.709600   45.863600       47.051199            1
4      46.699600   47.983600   46.226000       47.522800            1
5      47.240000   48.536800   46.788000       48.032800            1
6      48.192800   48.833200   47.628001       48.324800            1
7      48.510400   49.272800   47.980000       48.814001            1
8      48.938800   49.553600   48.407600       49.184401            1
9      49.271600   49.739600   48.726000       49.280401            1
10     49.252400   49.717200   48.690800       49.327200            1
11     49.180800   49.786401   48.735200       49.388000            1
12     49.238800   49.754401   48.835600       49.343600            0
13     49.266000   49.838401   48.855599       49.292001            0
14     49.269199   49.778401   48.831599       49.303600            1
15     49.265199   49.940801   48.978799       49.587601            1
16     49.584000   50.190801   49.261600       49.794801            1
17     49.825200   50.310801   49.360000       49.863600            1
18     49.874800   50.206801   49.352000       49.899200            1
19     49.862400   50.255601   49.410400       49.961600            1
20     49.881200   50.155601   49.436800       49.740399            0
21     49.681200   50.028800   49.286800       49.673999            0
22     49.658800   50.314800   49.400400       49.947599            1
23     49.918000   50.648400   49.714000       50.253600            1
24     50.066000   50.779600   49.773600       50.321999            1
25     50.296400   50.982400   49.962400       50.541600            1
26     50.464800   51.132800   50.143600       50.603600            1
27     50.418800   50.834000   49.971600       50.367200            0
28     50.208000   50.662000   49.770000       50.252000            0
29     50.218800   51.076401   49.910799       50.640401            1
...          ...         ...         ...             ...          ...
1317  301.398401  312.058002  288.869202      297.810803            0
1318  293.760400  305.027606  288.478406      296.787598            0
1319  297.720001  307.109607  290.656006      297.338000            1
1320  298.288000  305.584406  291.911206      295.153998            0
1321  297.928406  304.092804  291.414404      295.574396            1
1322  297.608002  302.694000  290.666803      295.010797            0
1323  297.721198  302.856799  290.917200      295.094397            1
1324  297.102795  302.164801  290.678400      295.972394            1
1325  297.054797  300.072400  288.336798      293.315192            0
1326  293.094397  295.776001  284.456799      288.810791            0
1327  292.174799  299.182404  283.124402      291.600391            1
1328  296.981604  304.537201  286.724402      296.857196            1
1329  303.599603  311.299200  295.189600      304.777197            1
1330  312.759601  326.833600  306.669202      321.459998            1
1331  332.879199  346.989600  325.873602      341.967999            1
1332  348.679199  360.029602  342.122003      354.918799            1
1333  358.666394  374.862006  353.714001      370.151996            1
1334  373.857196  391.929602  369.650403      386.122797            1
1335  391.828400  403.255200  379.838000      393.265198            1
1336  394.864398  407.417200  384.753601      398.715198            1
1337  402.664398  417.617200  393.250403      409.700800            1
1338  415.455603  428.561597  404.668005      419.177600            1
1339  425.470001  437.481598  411.126801      425.714398            1
1340  429.340796  452.349603  422.047998      444.810400            1
1341  450.773199  471.729602  437.429999      458.886798            1
1342  464.171198  480.897601  436.308795      462.233997            1
1343  458.398798  475.433600  431.008795      454.083997            0
1344  447.156000  468.294000  417.951996      449.212000            0
1345  429.434003  442.013995  395.906000      415.589996            0
1346  400.326001  415.315997  370.106000      393.835999            0

[1347 rows x 5 columns]

In [48]:
X = tsla_means.iloc[:, 0:-1].values
y = tsla_means.iloc[:, -1].values

In [57]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 101)

In [58]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

In [61]:
lr.fit(X_train, y_train)

D:\Anaconda\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [67]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = lr.predict(X_test)

print('Confusion Matrix:', confusion_matrix(y_test, y_pred))
print("Accuracy Score:", accuracy_score(y_test, y_pred))

Confusion Matrix: [[ 92  26]
 [ 19 133]]
Accuracy Score: 0.8333333333333334

In [68]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [69]:
y_pred_dtc = dtc.predict(X_test)

print('Confusion Matrix DTC:', confusion_matrix(y_test, y_pred_dtc))
print('Accuracy Score DTC:', accuracy_score(y_test, y_pred_dtc))

Confusion Matrix DTC: [[ 74  44]
 [ 47 105]]
Accuracy Score DTC: 0.662962962962963

In [83]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators = 1000)

rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [84]:
y_pred_rfc = rfc.predict(X_test)

print("Confusion Matrix RFC: ", confusion_matrix(y_test, y_pred_rfc))
print('Accuracy Score RFC: ', accuracy_score(y_test, y_pred_rfc))

Confusion Matrix RFC:  [[ 74  44]
 [ 39 113]]
Accuracy Score RFC:  0.6925925925925925

In [85]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train, y_train)
y_pred_gnb = gnb.predict(X_test)

print('Confusion Matrix: ', confusion_matrix(y_test, y_pred_gnb))
print('Accuracy Score: ', accuracy_score(y_test, y_pred_gnb))

Confusion Matrix:  [[112   6]
 [134  18]]
Accuracy Score:  0.48148148148148145

In [86]:
#LOGISTIC REGRESSION IS BEST!!!!!!!!!!!