In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
%matplotlib inline

In [2]:
start = '2015-01-05'
end = '2020-09-04'

eur_df = yf.download('EURUSD=X', start, end)

[*********************100%***********************]  1 of 1 completed

In [6]:
eur_df.drop('Volume', axis = 1, inplace = True)

In [7]:
eur_df.head()

                Open      High       Low     Close  Adj Close
Date
2015-01-05  1.195500  1.197590  1.188909  1.194643   1.194643
2015-01-06  1.193830  1.197000  1.188693  1.193902   1.193902
2015-01-07  1.187479  1.190000  1.180401  1.187536   1.187536
2015-01-08  1.183894  1.184806  1.175601  1.183600   1.183600
2015-01-09  1.179426  1.183830  1.176831  1.179607   1.179607

In [8]:
open_mean = []
high_mean = []
low_mean = []
close_mean = []

for i in range(len(eur_df['Adj Close'])):
    open_mean.append(eur_df['Open'][i-5:i].mean())
    high_mean.append(eur_df['High'][i-5:i].mean())
    low_mean.append(eur_df['Low'][i-5:i].mean())
    close_mean.append(eur_df['Adj Close'][i-5:i].mean())

In [9]:
data_dict = {'Open Mean' : open_mean,
             'High Mean' : high_mean,
             'Low Mean' : low_mean,
             'Adj Close Mean' : close_mean}

In [10]:
df_mean = pd.DataFrame(data_dict)

In [11]:
df_mean

      Open Mean  High Mean  Low Mean  Adj Close Mean
0           NaN        NaN       NaN             NaN
1           NaN        NaN       NaN             NaN
2           NaN        NaN       NaN             NaN
3           NaN        NaN       NaN             NaN
4           NaN        NaN       NaN             NaN
5      1.188026   1.190645  1.182087        1.187857
6      1.186329   1.188567  1.180065        1.186343
7      1.184210   1.186348  1.177457        1.184193
8      1.182249   1.185219  1.175989        1.182252
9      1.181147   1.184029  1.172714        1.181250
10     1.178042   1.180263  1.166634        1.178076
11     1.171915   1.175597  1.161954        1.171983
12     1.167208   1.170737  1.158208        1.167312
13     1.162606   1.167145  1.154471        1.162685
14     1.159269   1.164232  1.150905        1.159274
15     1.153419   1.158711  1.144055        1.153461
16     1.144960   1.151617  1.135791        1.144649
17     1.138039   1.147697  1.128927        1.137644
18     1.134445   1.142057  1.124209        1.134053
19     1.127801   1.136559  1.121210        1.127375
20     1.127619   1.136360  1.124493        1.127151
21     1.130896   1.137880  1.127536        1.130823
22     1.132615   1.138480  1.129374        1.132703
23     1.134412   1.140524  1.131301        1.134503
24     1.135061   1.142364  1.132360        1.135249
25     1.137732   1.144604  1.133040        1.137977
26     1.137934   1.144604  1.132616        1.138084
27     1.137716   1.142604  1.131769        1.137789
28     1.134969   1.139559  1.129458        1.135080
29     1.134790   1.138323  1.129243        1.134945
...         ...        ...       ...             ...
1446   1.147710   1.152655  1.145221        1.147930
1447   1.151880   1.156623  1.149277        1.152010
1448   1.156140   1.162856  1.154224        1.156202
1449   1.162318   1.168412  1.159719        1.162413
1450   1.166027   1.171973  1.163848        1.166109
1451   1.170431   1.175635  1.167658        1.170392
1452   1.176004   1.180993  1.172076        1.175915
1453   1.178635   1.181154  1.173052        1.178510
1454   1.178516   1.181738  1.173516        1.178391
1455   1.180402   1.184265  1.175216        1.180324
1456   1.182138   1.186355  1.176977        1.182123
1457   1.182166   1.185866  1.176056        1.182208
1458   1.182133   1.186154  1.176888        1.182216
1459   1.181674   1.186154  1.176869        1.181705
1460   1.180173   1.184301  1.175130        1.180127
1461   1.178630   1.183343  1.174609        1.178547
1462   1.177507   1.182433  1.175171        1.177348
1463   1.178867   1.184007  1.176919        1.178745
1464   1.181700   1.187211  1.179963        1.181519
1465   1.185849   1.190049  1.183571        1.185745
1466   1.186754   1.190138  1.183808        1.186739
1467   1.187793   1.191105  1.183212        1.187881
1468   1.186766   1.190542  1.182328        1.186791
1469   1.185085   1.188121  1.180517        1.185152
1470   1.182806   1.185829  1.178170        1.182895
1471   1.182775   1.186430  1.177364        1.182879
1472   1.181768   1.187110  1.178505        1.181799
1473   1.184116   1.189331  1.180483        1.184203
1474   1.186994   1.192674  1.183533        1.187093
1475   1.188789   1.194362  1.184494        1.188857

[1476 rows x 4 columns]

In [13]:
df_mean.dropna()

      Open Mean  High Mean  Low Mean  Adj Close Mean
5      1.188026   1.190645  1.182087        1.187857
6      1.186329   1.188567  1.180065        1.186343
7      1.184210   1.186348  1.177457        1.184193
8      1.182249   1.185219  1.175989        1.182252
9      1.181147   1.184029  1.172714        1.181250
10     1.178042   1.180263  1.166634        1.178076
11     1.171915   1.175597  1.161954        1.171983
12     1.167208   1.170737  1.158208        1.167312
13     1.162606   1.167145  1.154471        1.162685
14     1.159269   1.164232  1.150905        1.159274
15     1.153419   1.158711  1.144055        1.153461
16     1.144960   1.151617  1.135791        1.144649
17     1.138039   1.147697  1.128927        1.137644
18     1.134445   1.142057  1.124209        1.134053
19     1.127801   1.136559  1.121210        1.127375
20     1.127619   1.136360  1.124493        1.127151
21     1.130896   1.137880  1.127536        1.130823
22     1.132615   1.138480  1.129374        1.132703
23     1.134412   1.140524  1.131301        1.134503
24     1.135061   1.142364  1.132360        1.135249
25     1.137732   1.144604  1.133040        1.137977
26     1.137934   1.144604  1.132616        1.138084
27     1.137716   1.142604  1.131769        1.137789
28     1.134969   1.139559  1.129458        1.135080
29     1.134790   1.138323  1.129243        1.134945
30     1.133469   1.137803  1.130482        1.133584
31     1.135114   1.139303  1.132989        1.135297
32     1.135266   1.141149  1.133980        1.135438
33     1.136975   1.142810  1.135164        1.137093
34     1.138827   1.143846  1.136164        1.138855
...         ...        ...       ...             ...
1446   1.147710   1.152655  1.145221        1.147930
1447   1.151880   1.156623  1.149277        1.152010
1448   1.156140   1.162856  1.154224        1.156202
1449   1.162318   1.168412  1.159719        1.162413
1450   1.166027   1.171973  1.163848        1.166109
1451   1.170431   1.175635  1.167658        1.170392
1452   1.176004   1.180993  1.172076        1.175915
1453   1.178635   1.181154  1.173052        1.178510
1454   1.178516   1.181738  1.173516        1.178391
1455   1.180402   1.184265  1.175216        1.180324
1456   1.182138   1.186355  1.176977        1.182123
1457   1.182166   1.185866  1.176056        1.182208
1458   1.182133   1.186154  1.176888        1.182216
1459   1.181674   1.186154  1.176869        1.181705
1460   1.180173   1.184301  1.175130        1.180127
1461   1.178630   1.183343  1.174609        1.178547
1462   1.177507   1.182433  1.175171        1.177348
1463   1.178867   1.184007  1.176919        1.178745
1464   1.181700   1.187211  1.179963        1.181519
1465   1.185849   1.190049  1.183571        1.185745
1466   1.186754   1.190138  1.183808        1.186739
1467   1.187793   1.191105  1.183212        1.187881
1468   1.186766   1.190542  1.182328        1.186791
1469   1.185085   1.188121  1.180517        1.185152
1470   1.182806   1.185829  1.178170        1.182895
1471   1.182775   1.186430  1.177364        1.182879
1472   1.181768   1.187110  1.178505        1.181799
1473   1.184116   1.189331  1.180483        1.184203
1474   1.186994   1.192674  1.183533        1.187093
1475   1.188789   1.194362  1.184494        1.188857

[1471 rows x 4 columns]

In [27]:
def price_list(price):
    truth_list = []
    
    for i in range(len(price)):
        if i < len(price):
            if price[i-1] < price[i]:
                truth_list.append(1)
            else:
                truth_list.append(0)
    
    return truth_list

In [28]:
list_of_truths = price_list(close_mean)
list_of_truths

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 ...]

In [29]:
df_mean['Price Up'] = list_of_truths

In [32]:
df_mean.dropna(inplace = True)

In [37]:
df_mean.tail()

      Open Mean  High Mean  Low Mean  Adj Close Mean  Price Up
1471   1.182775   1.186430  1.177364        1.182879         0
1472   1.181768   1.187110  1.178505        1.181799         1
1473   1.184116   1.189331  1.180483        1.184203         1
1474   1.186994   1.192674  1.183533        1.187093         1
1475   1.188789   1.194362  1.184494        1.188857         1

In [36]:
df_mean['Price Up'] = df_mean['Price Up'].shift(periods = -1, fill_value = 1)

In [38]:
X = df_mean.iloc[:, 0:-1].values
y = df_mean.iloc[:, -1].values

In [41]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 101)

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score

lr = LogisticRegression()

lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

print("CM: ", confusion_matrix(y_test, y_pred))
print('Accuracy Score: ', accuracy_score(y_test, y_pred))

CM:  [[138  15]
 [126  16]]
Accuracy Score:  0.5220338983050847

D:\Anaconda\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [44]:
tryout = yf.download('EURUSD=X', start = '2020-09-07', end = '2020-09-11')

[*********************100%***********************]  1 of 1 completed

In [45]:
try_list = []

try_list.append(tryout['Open'].mean())
try_list.append(tryout['High'].mean())
try_list.append(tryout['Low'].mean())
try_list.append(tryout['Adj Close'].mean())

In [46]:
try_list

[1.1807821691036224,
 1.1855643093585968,
 1.1784375309944153,
 1.1808201968669891]

In [51]:
sample = np.array(try_list)

In [53]:
sample = sample.reshape(1, -1)

In [54]:
lr.predict(sample)

array([0], dtype=int64)

In [55]:
eur_df.head()

                Open      High       Low     Close  Adj Close
Date
2015-01-05  1.195500  1.197590  1.188909  1.194643   1.194643
2015-01-06  1.193830  1.197000  1.188693  1.193902   1.193902
2015-01-07  1.187479  1.190000  1.180401  1.187536   1.187536
2015-01-08  1.183894  1.184806  1.175601  1.183600   1.183600
2015-01-09  1.179426  1.183830  1.176831  1.179607   1.179607

In [57]:
close_list = []
for i in range(len(eur_df['Adj Close'])):
    close_list.append(eur_df['Adj Close'][i])

In [59]:
eur_df['Price Go Up'] = price_list(close_list)

eur_df['Price Go Up'] = eur_df['Price Go Up'].shift(-1, fill_value = 1)

In [61]:
eur_df.tail()

                Open      High       Low     Close  Adj Close  Price Go Up
Date
2020-08-28  1.182047  1.192037  1.181195  1.181963   1.181963            1
2020-08-31  1.191654  1.196358  1.188509  1.191824   1.191824            1
2020-09-01  1.193916  1.201129  1.193730  1.193902   1.193902            0
2020-09-02  1.192307  1.192435  1.182410  1.192321   1.192321            0
2020-09-03  1.184596  1.184806  1.178967  1.184736   1.184736            1

In [62]:
X_daily = eur_df.iloc[:, 0:-1].values
y_daily = eur_df.iloc[:, -1].values

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X_daily, y_daily, test_size = 0.2, random_state = 101)

In [64]:
lrII = LogisticRegression()

In [65]:
lrII.fit(X_train, y_train)

D:\Anaconda\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [66]:
y_pred = lrII.predict(X_test)

print('CM: ', confusion_matrix(y_test, y_pred))
print('AS: ', accuracy_score(y_test, y_pred))

CM:  [[143   0]
 [153   0]]
AS:  0.4831081081081081